spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/estatehub_auth
spring.datasource.username=root
spring.datasource.password=Sith#123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Configuration (Secret key is a Base64-encoded 256-bit key)
jwt.secret=9a67475c74263385750d0322c349ef2c4cf27e4e892d19213192031a02bb4e16
jwt.expiration=86400000

# API Gateway Mutual Authentication Key
app.api-key=ESTATEHUB_SECRET_KEY