spring.data.mongodb.uri=mongodb://localhost:27017/auth_db
spring.application.name=auth-service
server.port=8081



# JWT Security Configuration (Secret key is a Base64-encoded 256-bit key)
jwt.secret=9a67475c74263385750d0322c349ef2c4cf27e4e892d19213192031a02bb4e16
jwt.expiration=86400000

# API Gateway Mutual Authentication Key
app.api-key=ESTATEHUB_SECRET_KEY