version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: estatehub-mongodb
    restart: always
    ports:
      - "27018:27017"
    networks:
      - estatehub-network

  frontend:
    build:
      context: ./frontend
    container_name: estatehub-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - estatehub-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: estatehub-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - auth-service
      - property-service
      - agent-service
      - booking-service
      - payment-service
    networks:
      - estatehub-network

  auth-service:
    build:
      context: ./auth-service
    container_name: estatehub-auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    networks:
      - estatehub-network

  property-service:
    build:
      context: ./property-service
    container_name: estatehub-property-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    networks:
      - estatehub-network

  agent-service:
    build:
      context: ./agent-service
    container_name: estatehub-agent-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    networks:
      - estatehub-network

  booking-service:
    build:
      context: ./booking-service
    container_name: estatehub-booking-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    networks:
      - estatehub-network

  payment-service:
    build:
      context: ./payment-service
    container_name: estatehub-payment-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
    networks:
      - estatehub-network

networks:
  estatehub-network:
    driver: bridge

