spring.data.mongodb.uri=mongodb://localhost:27017/paymentdb
server.port=8085

# Security API Key Configuration
payment.api.key=estatehub-payment-secret-2026

# Database Configuration (H2 for Dev Profile)

# Mail Configuration (Mock/Console)
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mock
spring.mail.password=mock
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
