# Docker environment config connects to MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:mysql-server}:3306/${DB_NAME:agent_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Create / Update schema
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
