server.port=8082

spring.application.name=property-service

# Database Configuration (MongoDB Default for Local Dev)
spring.data.mongodb.uri=mongodb://localhost:27017/property_db

# Custom Application Properties
property.api.key=${PROPERTY_API_KEY:estatehub-property-secret-2026}

# OpenAPI Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
